POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Física, Matemática e Outras Bobagens",
    "author": "Guilherme Dias Simões",
    "url": "https://gdsimoes.com",
    "likes": 17
}

