DELETE http://localhost:3003/api/blogs/66f47affa1ffe1efddffe40c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdkc2ltb2VzIiwiaWQiOiI2NmYzNWEwYWNkMzlmYmNiZDU2YTUzNTgiLCJpYXQiOjE3MjcyOTc4MzEsImV4cCI6MTcyNzMwMTQzMX0.DeLaR4yMtypOvnIly8ZSrI4ZPtjy10QTWKMFjiULnWE